### ISSUE TITLE
add event-specific analytics event tracking

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/climate-fish-habitat#118]

**Comment by jordansread** [comment]
we kind of need to have production analytics and dev/QA, so that we can test the events are happening on dev. Assuming we can do that, events (bold are must haves):
- [x] **hovered over wally trends**
- [x] **button clicks for GDD pattern (reset, finished, skip)**
- [x] **tried to draw GDD pattern (any dots)**
- [x] value of GDD guess
- [x] **hovered over sankey**
- [ ] clicked on map button
- [ ] within map, clicked on a lake
- [x] **viewed chapter (all chapters, yes/no). Each chapter is an event**
- [x] **left page to view publication**
- [x] left page via any link
- [ ] clicked on sankey toggle

Others?

**Comment by jordansread** [comment]
Have a bunch of these in #117 , but will want some feedback on whether or not this is a good way to do events.

**Comment by jordansread** [comment]
For some reason these events aren't sent in Safari (when the js is within the svg?). Update: it looks like the hover ones work for sankey and wally trends but none of the events within the GDD guess fig work on Safari.

**Comment by jordansread** [comment]
@jiwalker-usgs can you add the link click event tracking that you mentioned?

**Comment by jordansread** [comment]
and the chapter views?

**Comment by jiwalker-usgs** [comment]
should we treat the map button like an outbound link?

**Comment by jordansread** [comment]
yes
